Camera
Jaete/Clawtopia pull request #10
Opened 2024-07-27 01:19 UTC by shizuo-hachi

- add: CameraController.cs
- add: camera
Controle de câmera ao aproximar o mouse das bordas da tela.
Zoom de câmera com mouse wheel e page up (aumenta zoom) e page down (diminui zoom).

2024-07-27 12:29 UTC, Jaete requested changes

2024-07-27 12:29 UTC, Jaete commented on Scripts/Systems/Camera/CameraController.cs
> +        base.PositionSmoothingSpeed = 3.5f;
o "base" é redundante

2024-07-27 12:29 UTC, Jaete commented on Scripts/Systems/Camera/CameraController.cs
> +
Aqui te faço uma pergunta: Consegue descobrir se tem algum signal nativo da Godot que verifica quando a viewport muda de tamanho? O tamanho dela é sempre o mesmo a menos que o jogador redimensione a janela, não precisa ficar adicionando a variável em todo frame

2024-07-27 12:29 UTC, Jaete commented on Scripts/Systems/Camera/CameraController.cs
> +        var bottomThreshold = viewportSize.Y - Sensitivity;
O mesmo aqui, sensitivity é uma constante e, até que a viewport mude, também é.

2024-07-27 12:29 UTC, Jaete commented on Scripts/Systems/Camera/CameraController.cs
> +    }
O zoom out ficou com um limite bem extenso, se der o zoom out completo os sprites viram só alguns pixels de tamanho.

2024-07-27 12:29 UTC, Jaete commented on Scripts/Systems/Camera/CameraController.cs
> +        Position += direction * Speed; // Equivalent to 'position +='
Ficou bem lento. Você me disse que rápida estava incomodando, mas ela precisa estar num ponto onde seja rápida o suficiente pro jogador poder visualizar partes distantes do mapa rapidamente. Talvez remover o smoothing ajude.

2024-07-27 16:02 UTC, Jaete requested changes

2024-07-27 16:02 UTC, Jaete commented on Scripts/Systems/Camera/CameraController.cs
> +        Position += direction * Speed; // Equivalent to 'position +='
Algo mais que notei: Preciso que a câmera possa mover diagonalmente também quando o mouse estiver no canto da tela.

2024-08-01 19:08 UTC, shizuo-hachi commented on Scripts/Systems/Camera/CameraController.cs
> +        base.PositionSmoothingSpeed = 3.5f;
quando eu tava descobrindo como fazia eu encontrei as propriedades em GDScript, aí demorei um pouco pra encontrar elas em C# e fui tentando outras coisas...
já arrumei aqui

2024-08-01 20:11 UTC, shizuo-hachi commented on Scripts/Systems/Camera/CameraController.cs
> +
Pelo que eu vi aqui o Viewport é parte do rootnode, mas só é possível modificar as propriedades dele pelo project settings. Aparentemente a engine resolve isso sozinha, eu transformei viewportSize e mousePosition em propriedades da classe e inicializei o viewportSize no _Ready. Se eu encontrar um signal eu implemento uma função, mais pra frente dá pra testar isso também. Pelo menos quando mexe na janela não dá erro nenhum, acho que poderia dar problema só se desse pra alterar a resolução, mas eu imagino que o window width override e window height override (nos advanced settings do Project Settings/Display/Window deve dar conta disso...)

Beleza, eu tava testando aqui, e o principal problema é que quando faz o resize da janela o viewport continua o mesmo. aí ele coloca as bordas no quadrante superior esquerdo e ativa o scroll da tela a partir dali... 

Alterei o stretch mode do projeto pra canvas_items e deu certo. Eu acho que por enquanto é isso.

2024-08-01 20:33 UTC, shizuo-hachi commented on Scripts/Systems/Camera/CameraController.cs
> +    }
Diminui o zoom mínimo pra 0.5f

2024-08-01 20:42 UTC, shizuo-hachi commented on Scripts/Systems/Camera/CameraController.cs
> +    }
Tava testando o Display Server aqui, mas ele só muda a janela, não acessa o Viewport, aí quando altera o tamanho da janela buga o lugar onde ativa o scroll também...

2024-09-08 15:55 UTC, Jaete commented on .idea/.idea.Clawtopia Cs/.idea/libraries/GdSdk_Master.xml
Eu também fiz isso mas já deletei na main, mas quando for fazer pr não manda junto seus arquivos de configuração de IDE (pastas .idea, .vs, .vscode)

2024-09-08 15:55 UTC, Jaete commented on Clawtopia Cs.csproj.old.3
Esses .old não envia também

2024-09-08 15:55 UTC, Jaete commented on Scripts/Systems/Camera/CameraController.cs
Faltou só aquele problema da mudança de tamanho da janela. Seu código resolve ele sem precisar detectar novamente a viewport?

Se sim, tudo bem.

Se por acaso ainda precisar disso, você faz o seguinte:

GetViewport().SizeChanged += FunçãoPraLerAViewportDeNovo <= Isso aqui vai conectar ao signal de SizeChanged que existe na viewport pra essa função que você criaria pra salvar o VisibleRect novamente.

Aqui tem um exemplo com uns ajustes que eu tinha feito no código inicial antes de você aplicar as outras funcionalidades. Eu ia deixar pra você descobrir sozinho mas isso pode ajudar também: [camera.txt](https://github.com/user-attachments/files/16922792/camera.txt)

E aí esse código aqui também resolve um problema que eu percebi depois: O jogo continua detectando a posição do mouse fora da tela, se você der um alt-tab por exemplo. O ideal seria implementar um pause automático, mas como ainda não temos, deixei esse código aí.

2024-09-09 01:50 UTC, shizuo-hachi commented on Clawtopia Cs.csproj.old.3
Eu achei que esses arquivos tinham vindo junto com o projeto. Tem alguma forma de configurar a exclusão automaticamente?

2024-09-09 10:44 UTC, Jaete commented on Clawtopia Cs.csproj.old.3
Tem duas opções: Você dá o ```git add . ``` e depois dá ```git restore --staged arquivo-pra-tirar``` ou você configura o arquivo .gitignore

Seria algo como `/.idea` para as pastas de config de IDE, de acordo com essa doc: [aqui](https://git-scm.com/docs/gitignore)

Pros arquivos .old eu **acho** que seria algo como `*.csproj.old.*`

2024-09-28 19:52 UTC, closed without merging